# Generated by Django 3.2.19 on 2024-02-11 09:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "developer_name",
                    models.CharField(
                        default="willisaplication",
                        max_length=255,
                        verbose_name="developer name",
                    ),
                ),
                (
                    "database_name",
                    models.CharField(
                        default="RDS", max_length=255, verbose_name="database name"
                    ),
                ),
                (
                    "record",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="object pk"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("data_entry", "data_entry"),
                            ("data_processing", "data_processing"),
                            ("data_deletion", "data_deletion"),
                            ("data_cleaning", "data_cleaning"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="reason",
                    ),
                ),
                (
                    "object_representation",
                    models.TextField(verbose_name="object representation"),
                ),
                (
                    "action",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "create"),
                            (1, "update"),
                            (2, "delete"),
                            (3, "access"),
                        ],
                        db_index=True,
                        verbose_name="action",
                    ),
                ),
                ("changes", models.JSONField(null=True, verbose_name="change message")),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
            ],
            options={
                "verbose_name": "log entry",
                "verbose_name_plural": "log entries",
                "ordering": ["-timestamp"],
                "get_latest_by": "timestamp",
            },
        ),
    ]
