# Generated by Django 3.2.19 on 2024-02-11 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditlog', '0016_auto_20240210_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='record',
            new_name='object_pk',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='object_representation',
            new_name='object_repr',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='database_name',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='developer_name',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='reason',
        ),
        migrations.AddField(
            model_name='logentry',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actor'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='additional_data',
            field=models.JSONField(blank=True, null=True, verbose_name='additional data'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='object_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='object id'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='serialized_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='changes',
            field=models.TextField(blank=True, verbose_name='change message'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp'),
        ),
    ]
