# Generated by Django 3.2.19 on 2024-05-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0017_alter_logentry_database_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='changes',
            new_name='change_value',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='developer_name',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='object_representation',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='record',
        ),
        migrations.AddField(
            model_name='logentry',
            name='event_column',
            field=models.TextField(default='None', verbose_name='event column'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='event_table',
            field=models.CharField(default='None', max_length=255, verbose_name='event table'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='event_type',
            field=models.CharField(blank=True, choices=[('data_entry', 'data_entry'), ('data_processing', 'data_processing'), ('data_deletion', 'data_deletion'), ('data_cleaning', 'data_cleaning')], max_length=255, null=True, verbose_name='event_type'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='identifier',
            field=models.CharField(db_index=True, default='None', max_length=255, verbose_name='identifier'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='source',
            field=models.CharField(default='aplication', max_length=255, verbose_name='source'),
        ),
    ]
