# Generated by Django 3.2.19 on 2024-05-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0018_auto_20240506_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='source',
            field=models.CharField(default='application', max_length=255, verbose_name='source'),
        ),
    ]
