# Generated by Django 3.2.19 on 2024-02-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0018_remove_logentry_changes_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("data_entry", "data_entry"),
                    ("data_processing", "data_processing"),
                    ("data_deletion", "data_deletion"),
                    ("data_cleaning", "data_cleaning"),
                ],
                max_length=255,
                null=True,
                verbose_name="reason",
            ),
        ),
    ]
