# Generated by Django 3.2.19 on 2025-06-07 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditlog', '0019_alter_logentry_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete'), ('access', 'access')], db_index=True, max_length=255, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='source'),
        ),
    ]
